import { z } from "zod";

// Schema for the script generated by the LLM
export const ScriptItemSchema = z.object({
  textOverlay: z.string(),
  voiceoverText: z.string(),
  sceneImage: z.string(),
});

export type ScriptItem = z.infer<typeof ScriptItemSchema>;

// Schema for the final synchronized payload expected by the frontend (Remotion player)
export const SynchronizedScriptSchema = z.object({
  durationInFrames: z.number(),
  textOverlay: z.string(),
  voiceoverText: z.string(),
  audioUrl: z.string(),
  sceneImage: z.string(),
});

export type SynchronizedScript = z.infer<typeof SynchronizedScriptSchema>;

export type TTSAudioResult = {
  audioUrl: string;
  durationInSeconds: number;
};

/**
 * 1. Accepts an array of strings (voiceoverText).
 * 2. Makes an async call to a TTS API (mocked for MVP).
 * 3. Returns dummy audio URLs and a hardcoded duration of 3 seconds.
 */
export async function generateTTSAudio(voiceoverTexts: string[]): Promise<TTSAudioResult[]> {
  // CRITICAL: MVP Mock Implementation
  // Later we can switch to OpenAI/ElevenLabs SDK or use native Next.js `fetch`.
  const promises = voiceoverTexts.map(async (text) => {
    // Simulate slight network delay for realism
    await new Promise((resolve) => setTimeout(resolve, 300));

    return {
      audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3", // Dummy URL
      durationInSeconds: 3, // Hardcoded 3 seconds
    };
  });

  return Promise.all(promises);
}

/**
 * Real implementation example (commented out for post-MVP phase).
 * Demonstrates using Next.js 14 native fetch.
 */
/*
export async function generateRealTTSAudio(voiceoverTexts: string[]): Promise<TTSAudioResult[]> {
  return Promise.all(voiceoverTexts.map(async (text) => {
    const response = await fetch("https://api.openai.com/v1/audio/speech", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${process.env.OPENAI_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "tts-1",
        voice: "alloy",
        input: text,
      })
    });
    
    if (!response.ok) {
      throw new Error("Failed to generate TTS audio");
    }
    
    // Convert to ArrayBuffer, save to Azure Blob / AWS S3, and calculate exact duration here.
    // ...
    
    return {
      audioUrl: "https://your-storage-bucket.com/audio-file.mp3",
      durationInSeconds: 4.2 
    };
  }));
}
*/

/**
 * 4. Middleware function that takes the LLM's JSON script array and TTS audio URLs.
 * Maps audio URLs back into the JSON array objects, creating a `SynchronizedScript` type.
 */
export function synchronizeScriptAndAudio(
  scriptItems: ScriptItem[],
  audioResults: TTSAudioResult[],
  fps: number = 30
): SynchronizedScript[] {
  if (scriptItems.length !== audioResults.length) {
    throw new Error("Mismatch: The number of script items does not match the TTS audio results.");
  }

  return scriptItems.map((item, index) => {
    const audioResult = audioResults[index];

    // Calculate duration in frames: durationInSeconds * framesPerSecond
    const durationInFrames = Math.ceil(audioResult.durationInSeconds * fps);

    return {
      durationInFrames,
      textOverlay: item.textOverlay,
      voiceoverText: item.voiceoverText,
      audioUrl: audioResult.audioUrl,
      sceneImage: item.sceneImage,
    };
  });
}

/**
 * 5. Main orchestration function to generate the final synchronized payload 
 * to be consumed by the frontend.
 */
export async function processMediaPipeline(items: ScriptItem[], fps: number = 30): Promise<SynchronizedScript[]> {
  // Extract all voiceover strings
  const voiceoverTexts = items.map((item) => item.voiceoverText);

  // Generate TTS Audio (currently the MVP mock)
  const audioResults = await generateTTSAudio(voiceoverTexts);

  // Map everything back together into a final payload
  return synchronizeScriptAndAudio(items, audioResults, fps);
}
